version: '3'

services:
  vite_docker:
    image: camilbenameur/4ailcbenameurnguyen:frontend-vite-server
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/srv/app" 
    container_name: vite-server
    working_dir: /srv/app

  flask_server:
    image: flask-server
    ports:
      - "5000:5000"
    volumes:
      - "./backend/:/srv/app"
    container_name: flask-server
    working_dir: /srv/app

  my_redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: myredis
