name: Build and Push Frontend Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Frontend Docker Image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t camilbenameur/4ailcbenameurnguyen:frontend-vite-server -f project/frontend/vite-project/Dockerfile .
      env:
        DOCKER_CLI_AGGREGATE: 1
        DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Frontend Docker Image
      run: docker push camilbenameur/4ailcbenameurnguyen:frontend-vite-server
