name: Vite CI

on:
  push:
    branches:
      - main
      - camilbenameur/refactor-api
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set NPM_CONFIG_CACHE
      run: export NPM_CONFIG_CACHE=$(npm config get cache)
      working-directory: project/frontend/vite-project

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci
      working-directory: project/frontend/vite-project

    - run: npm run build --if-present
      working-directory: project/frontend/vite-project
    - run: npm run lint
      working-directory: project/frontend/vite-project
